### PR TITLE
Fixed blocked pop ups

### PR DESCRIPTION
**Pull request by Patrokl42**
Fixed blocked pop-ups on mozilla and mobile browsers.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@Patrokl42 Thanks for contribution :+1: 
Could you explain the flow and why it's fixing the issue

**Comment by Patrokl42** [comment]
> @Patrokl42 Thanks for contribution 
> Could you explain the flow and why it's fixing the issue?

Browsers like mozilla blocked pop-ups created on async function.
I create pop-up before request sent, then change url.

**Comment by alexandrtovmach** [comment]
But pop-up initialization still inside async function

**Comment by Patrokl42** [comment]
> But pop-up initialization still inside async function

Here is more about this problem and solution.
https://www.mai1015.com/javascript/2019/05/23/javascript-window-open-async/

**Review by alexandrtovmach — APPROVED** [review]

**Comment by alexandrtovmach** [comment]
@Patrokl42 Thanks for contribution :muscle: 
Published in [1.3.0](https://www.npmjs.com/package/react-twitter-login/v/1.3.0)

**Pull request merged**
