### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jigarvakil**
updating peer dependency

### CODE REVIEW

**Comment by tgray017** [comment]
Could someone merge in this change please? This should resolve the same issue I'm running into. cc @alexandrtovmach 
Related: https://github.com/alexandrtovmach/react-twitter-login/issues/26

**Review by alexandrtovmach — CHANGES_REQUESTED** [review]
Could you replace it with
```
 ​    ​"react"​: ​"​>=16​"​, 
 ​    ​"react-dom"​: ​"​>=16​"
```

**Comment by tgray017** [comment]
@alexandrtovmach opened up a new PR with the fix above: https://github.com/alexandrtovmach/react-twitter-login/pull/32

**Comment by alexandrtovmach** [comment]
Closed as resolved in #31

**Pull request closed without merging**
